In [2]:
# 問題１

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

## 行列積の公式より

１列目
(-1) * 0 + 2 * 0 + 3 * 2 = 6,   4 * 0 + (-5)* 0 + 6 * 2 = 12,   7 * 0 + 8 * 0 + (-9) * 2 = -18  

２列目
(-1) * 2 + 2 * 2 + 3 * 9　= 29,   4 * 2 + (-5)* 2 + 6 * 9 = 52,   7 * 2 + 8 * 2 + (-9) * 9 = -51  　

３列目
(-1) * 1 + 2 * (-8) + 3 * (-1) = -20,   4 * 1 + (-5)* (-8) + 6 * (-1) = 38,   7 * 1 + 8 * (-8) + (-9) * (-1) = -48  

よって
a_ndarray * b_ndarray = np.array([6, 29, -20], [12, 52, 38], [-18, -51, -48])


In [16]:
# 問題２

ab_ndarray = a_ndarray @ b_ndarray
ab_ndarray


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [99]:
# 問題３

a_a = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_b = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# パターン１
x = np.zeros((3, 3))
x[0][0] = a_a[0][0] * b_b[0][0] + a_a[0][1] * b_b[1][0] + a_a[0][2] * b_b[2][0]
x[0][1] = a_a[0][0] * b_b[0][1] + a_a[0][1] * b_b[1][1] + a_a[0][2] * b_b[2][1]
x[0][2] = a_a[0][0] * b_b[0][2] + a_a[0][1] * b_b[1][2] + a_a[0][2] * b_b[2][2]
x[1][0] = a_a[1][0] * b_b[0][0] + a_a[1][1] * b_b[1][0] + a_a[1][2] * b_b[2][0]
x[1][1] = a_a[1][0] * b_b[0][1] + a_a[1][1] * b_b[1][1] + a_a[1][2] * b_b[2][1]
x[1][2] = a_a[1][0] * b_b[0][2] + a_a[1][1] * b_b[1][2] + a_a[1][2] * b_b[2][2]
x[2][0] = a_a[2][0] * b_b[0][0] + a_a[2][1] * b_b[1][0] + a_a[2][2] * b_b[2][0]
x[2][1] = a_a[2][0] * b_b[0][1] + a_a[2][1] * b_b[1][1] + a_a[2][2] * b_b[2][1]
x[2][2] = a_a[2][0] * b_b[0][2] + a_a[2][1] * b_b[1][2] + a_a[2][2] * b_b[2][2]
print(x)

# パターン２
result = []
for i, j, k in a_a:
    tmp = []
    for ii, jj, kk in zip(*b_b):
        tmp.append(i * ii + j * jj + k * kk)
    result.append(tmp)
print(result)


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


In [22]:
#　　問題4

def matrix_multiplication(A, B):
    a_rows, a_cols = len(A), len(B[0])  # A の行数及び列数
    b_rows, b_cols = len(A), len(B[0])  # B の行数及び列数

    # (A_rows, B_cols) の0で初期化した行列を作成する。
    ret = [[0 for j in range(b_cols)] for i in range(a_rows)]
    
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                ret[i][j] += A[i][k] * B[k][j]

    return ret

matrix_multiplication(a_ndarray, b_ndarray)


[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]

In [101]:
# 問題５

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def matrix_multiplication(A, B):
    a_rows, a_cols = len(A), len(B[0])  # A の行数及び列数
    b_rows, b_cols = len(A), len(B[0])  # B の行数及び列数

    if a_cols != b_rows:
        print("列数と行数が合っていないため行列積の計算はできません！")
        return None

    # (A_rows, B_cols) の0で初期化した行列を作成する。
    ret = [[0 for j in range(b_cols)] for i in range(a_rows)]
    
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                ret[i][j] += A[i][k] * B[k][j]

    return ret

matrix_multiplication(d_ndarray, e_ndarray)


列数と行数が合っていないため行列積の計算はできません！


In [104]:
# 問題６

f_ndarray = np.transpose(e_ndarray)

matrix_multiplication(d_ndarray, f_ndarray)

[[25, -16], [-76, 49]]